CC=clang++
FLAGS=-Wall -O3 -pedantic -std=c++11
DFLAGS=-Wall -Og -g -pedantic -std=c++11
EXEC=a-star.out
DEXEC=a-star_debug.out


all:
	$(CC) $(FLAGS) *.cpp -o $(EXEC)

debug:
	$(CC) $(DFLAGS) *.cpp -o $(DEXEC)
